BASE_OUTPUT_DIR: FiCell-EXAMPLE

SCE_INPUT:
- id: Astro_500
  sce_path: ./example/Signac_obj/Astro_500.rds
  cts_score_path: ./example/sclinker_score/Astro_Lcluster.txt
- id: L2_3_IT_500
  sce_path: ./example/Signac_obj/L2_3_IT_500.rds
  cts_score_path: ./example/sclinker_score/L2_3_IT_Lcluster.txt
    
GWAS_SUMSTATS_INPUT:
- id: MDD
  path: ./example/gwas/MDD.sumstats.gz
- id: SCZ
  path: ./example/gwas/SCZ.sumstats.gz
- id: intelligence
  path: ./example/gwas/Intelligence.sumstats.gz

WINDOW_DEFINITION:
    max_peak_TSS_distance:
        500000
    
SNP_COORDINATE:
    hg38:
        data/hm3SNP-coordinate-hg38.tsv
    hg19:
        data/hm3SNP-coordinate-hg19.tsv
    
TSS_COORDINATE_hg19:
    data/IGVF_portal_genes_file.tsv

BASELINE_MODEL_DIR:
    data/ldsc/baseline_v1.2
